services:
  mysql:
    image: mysql:8.0
    container_name: manga-mysql
    environment:
      MYSQL_DATABASE: manga_db
      MYSQL_USER: manga
      MYSQL_PASSWORD: manga
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:    
      - mysql_data:/var/lib/mysql 
      - ./db/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
